stages:
  - build
  - test
  - deploy
variables:
    IMAGE_TAG: "master:4567/root/tutorial"
before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://master:4567

build_image:
  tags:
    - my-runner
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy_image:
  tags:
    - my-runner
  stage: deploy
  script:
    - docker service update --image $(docker inspect --type image --format '{{index .RepoDigests 0}}' $IMAGE_TAG:latest) ello

  environment:
    name: $CI_ENVIRONMENT_NAME
